services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://datos:3306/flashlyrics?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: mister
      DB_PASSWORD: 7estamism0
    depends_on:
      datos:
        condition: service_healthy
      traduccion:
        condition: service_started
  traduccion:
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - lt-local:/home/libretranslate/.local
    container_name: traduccion
  datos:
      image: mysql:latest
      ports:
        - "3307"
        - "3306"
      environment:
        MYSQL_ROOT_PASSWORD: 1i1i1@1@xd
        MYSQL_PASSWORD: 7estamism0
        MYSQL_DATABASE: flashlyrics
        MYSQL_USER: mister
      restart: always
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 10s
        retries: 10
      container_name: datos
  frontend:
    depends_on:
      backend:
        condition: service_started
    build:
      context: ./FlashLyricsFrontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4020:4020"
volumes:
  lt-local:
